version: "3.7"
services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"

  ingress:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./ingress.yaml:/etc/envoy/envoy.yaml
    expose:
      - "1999"
      - "8001"
    ports:
      - "1999:1999"
      - "8001:8001"

  egress:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./egress.yaml:/etc/envoy/envoy.yaml
    expose:
      - "10000"
      - "8002"
    ports:
      - "10000:10000"
      - "8002:8002"